1

diff --git a/.github/workflows/prvalidation.yml b/.github/workflows/prvalidation.yml
--- a/.github/workflows/prvalidation.yml
+++ b/.github/workflows/prvalidation.yml
@@ -12,6 +12,6 @@ jobs:
       - name: Check branches
         run: |
           if [ ${{ github.head_ref }} != "next" ] && [ ${{ github.base_ref }} == "main" ]; then
-            echo "Merge requests to main branch are only allowed from next branch."
+            printf '%s\n' "Test case x failed" >&2
             exit 1
           fi
